# Generated by Django 5.1.2 on 2024-11-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
