# Generated by Django 5.1.2 on 2024-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_billing_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='stripe_session_id',
        ),
        migrations.AddField(
            model_name='billing',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
